### ISSUE TITLE
Flaky test: crashed pods may temporarily be "ready" on instantiation.

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroachdb-cloudformation#13]
A pod may be in the ready state temporarily but then crash moments later. We should ensure that the pod is ready for some period of time before we say "create complete".

**Comment by asubiotto** [comment]
I will work on this ASAP as part of fixing https://github.com/cockroachdb/cockroach/issues/22424. We need to split our liveness and readiness checks and make the readiness checks a bit more custom (check for draining status + ability to issue a SQL command like `SELECT 1`)

**Comment by asubiotto** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/22911
