### ISSUE TITLE
enable restore dataset from backup 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroachdb-cloudformation#31]
@nstewart some of the oltpbenchmark benchmarks such as smallbank takes a while to generate the dataset.  Is there AWS or Google storage where backup files can be restored from?  How about copying the backup files to the master K8s node and run caddy?

**Comment by robert-s-lee** [comment]
thinking later (to accept the license key).  That will enable the demo of enterprise features sets as well easily.  I have backup files set for various SF factors (1,2,4,8).

**Comment by nstewart** [comment]
OK -- we can update this to accept a license key.
